### ISSUE TITLE
Unable to resolve Scandit packages

### ISSUE THREAD

**Issue by MattAydin** [Scandit/datacapture-spm#5]
Hi there, 

When trying to resolve the `datacapture-spm` package we are receiving mismatched checksum errors: 

<img width="996" alt="image" src="https://github.com/Scandit/datacapture-spm/assets/1391489/204c2736-f29a-46ad-a65b-098f28567cc5">

When downloading a random zip and calculating the checksum locally it doesn't match. 

Could you please have a look? We now pinned the package to 6.19.3 to continue our work.

**Comment by ScanditSupport** [comment]
Hi @MattAydin,

Please accept our apologies for the issue, the spm packages should be fixed now.
Could you please clear the spm caches and try again with 6.21.2 SDK?

**Comment by MattAydin** [comment]
Hello. Thank you for resolving this issue. I can confirm it works.

**Comment by ScanditSupport** [comment]
Hi @MattAydin,

Glad to help, do not hesitate to contact us if you encounter any problems!
You can reach out to us directly via support@scandit.com .
